- tsconfig.json
Changed module to CommonJS. For runtimes like React Native, AMD doesn't work. This change was tested on Angular application and React.
Changed the AMD module to CommonJS in typescript configuration.
Running applications using beagle-react and beagle-angular.
AMD module to CommonJS
> Changed AMD module to CommonJS

- package.json
> Releases v1.1.0

- .github/workflows/publish.yml
- .github/workflows/validate.yml
Added cache clean before install. 
Added cache clean before install. 
On PR to master must run cache clean.
Added cache clean before install.
> added cache clean before install

- CODEOWNERS
Adding James, Tayrone and Hector to codeowners
> Adding James, Tayrone and Hector to codeowners

- __tests__/unit/old-structure/actions/addChildren/addChildren.spec.ts
- src/action/add-children.ts
closes #287 
Added lower case comparison for addChildren mode
Created test case
Adds lower case comparison
> Adds toLowerCase before mode comparison

- package.json
> Release new version - 1.5.0

- README.md
Fixed the main readme file.
N/A
N/A
N/A
> Enhances the text and fixes some deprecated code

- __tests__/unit/service/analytics/index.spec.ts
- src/service/analytics/index.ts
- src/service/analytics/types.ts
Removed queue logic
Removed any code or tests related to the queue implementation
Queue related logic should not be available in the beagle service config
> Removes queue logic

- bin/copy-files.js
- package.json
> Release 1.6.0

- bin/copy-files.js
Fixed the case of the readme file in the copy script. It causes problem in linux, since the filesystem is case sensitive.
Fixed the case
Check the code and the filename
> fixes readme filename

- src/beagle-view/index.ts
- src/beagle-view/navigator/types.ts
- src/beagle-view/types.ts
- src/service/beagle-service/index.ts
- src/service/beagle-service/types.ts
- src/service/network/types.ts
**Related PR**
- https://github.com/ZupIT/beagle-web-react/pull/185
- https://github.com/ZupIT/beagle-web-angular/pull/237
Updated Route interface according to this issue https://github.com/ZupIT/beagle/issues/1398
Added the new HttpData property to the Route interface and used it when fetching the view
Passing the new property to the route structure in the payload
> Updates interface

- __tests__/unit/beagle-view/navigator.spec.ts
- src/beagle-view/index.ts
- src/beagle-view/navigator/index.ts
- src/beagle-view/navigator/types.ts
- src/service/beagle-service/types.ts
Make fixes based on my comments
> Navigation state 2

- package.json
> Releases 1.7.0

- package.json
> Release 1.9

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/publish.yml
- .github/workflows/validate.yml
- CONTRIBUTING.md
- src/beagle-view/render/types.ts
Renamed branch master to main on github actions
Link to the issue https://github.com/ZupIT/beagle/issues/1577
> feat: Rename branch to main

- __tests__/integration/beagle-keep/assertions/render/__snapshots__/labels.spec.ts.snap
- __tests__/integration/beagle-keep/assertions/render/details/__snapshots__/create.spec.ts.snap
- __tests__/unit/old-structure/styles-mocks.ts
- src/beagle-view/render/styling.ts
Added support for topLeft, topRight, bottomLeft, bottomRight in corner radius.
I changed the corner radius interface.
{
"_beagleComponent_": "beagle:container",
"style": {
"flex": {
"flexDirection": "COLUMN",
"alignItems": "CENTER",
"justifyContent": "CENTER"
},
"size": {
"height": {
"value": 300,
"type": "REAL"
},
"width": {
"value": 300,
"type": "REAL"
}
},
"borderColor": "#FF0000",
"borderWidth": 20,
"cornerRadius": {
"topRight": 0,
"bottomRight": 50,
"topLeft": 50,
"bottomLeft": 0
}
}
}
Test with this Json.
Closes #https://github.com/ZupIT/beagle/issues/1632
Closes #https://github.com/ZupIT/beagle/issues/1719
> Fix corner radius

- CODEOWNERS
> Updates code owners

- CONTRIBUTING.md
- README.md
- Added new README.
- Added new Contributing Guide. 
> Fix: Read me and Contributing Guide

- .github/workflows/validate.yml
- README.md
Added best practices badge to REAME file
> Adds best practices badge

- SECURITY.md
> Adds security md file

- .github/dependabot.yml
> Updates dependabot schedule

- .github/workflows/header.license-checker.yml
- horusec-config.json
Updates header license checker
> Updates header action

- SECURITY.md
Updates security file with new e-mail
> updates security file

- package.json
Signed-off-by: Arthur Bleil <arthur.bleil@zup.com.br>
> update: version

- src/utils/expression.ts
Signed-off-by: Arthur Bleil <arthur.bleil@zup.com.br>
> fix isContextExpression parameter type validation
